---

- hosts: all
  become: true

  tasks:
    - name: Reconfigure sshd daemon
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'

    - name: Restart sshd service
      service:
        name: sshd
        state: restarted
